trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    set -eo pipefail
    set -u
    tag=`git describe --tags --abbrev=0`
    echo '##vso[task.setvariable variable=tag]'$tag
  displayName: 'Retrieve tag'
- script: |
    set -eo pipefail
    set -u
    echo '$(tag)'
  displayName: 'Show tag'
